### ISSUE TITLE
Regarding addition to the main factor repository

### ISSUE THREAD

**Issue by razetime** [andreaferretti/factor-tutorial#9]
I would like to update this tutorial for Factor 0.99 and add some sections for addition to the main factor repository, in the help pages. 

I'd like to know what license this would be under, so we can use it in the repository. factor/factor is under the BSD 2-clause simplified license. A compatible license or using the same license would be good.

**Comment by mrjbq7** [comment]
And if @andreaferretti would like, we could merge this into Factor as "Your Second Program" or something built into the Browser, and kept up-to-date.

**Comment by andreaferretti** [comment]
I would be very happy if this was used and maintained! I did not know that version 0.99 is coming, I thought development had unfortunately stalled. You can add it to the main factor repository, either in help pages or in the browser however you see fit!

Here I grant you the BSD 2-clause simplified license :-) Or should I write it somewhere more formally?

**Comment by mrjbq7** [comment]
That's awesome, thank you!!
